config/routes.rb
Rails.application.routes.draw do
  # devise
  root 'comments#index'
  get 'comments/index'
  devise_for :users, controllers: { registrations: 'users/registrations' }

  # 通知機能
  get '/users/notifications' => 'notifications#index'

  # チャットルームのルーティング
  resources :users, only: %i[index show destroy]
  resources :messages, only: [:create]
  resources :rooms, only: %i[create show index]

  # 退会機能
  delete 'destroy_user', to: 'users#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy

  has_many :users, through: :entries

  has_many :notifications, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  def create
    @room = Room.create
    @entry1 = Entry.create(room_id: @room.id, user_id: current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(room_id: @room.id))
    redirect_to "/rooms/#{@room.id}"
  end

  def show
    @room = Room.find(params[:id])
    if Entry.where(user_id: current_user.id, room_id: @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
      current_user.passive_notifications.where(room_id: @room).update(checked: true)
    else
      redirect_back(fallback_location: root_path)
    end
    @notifications = current_user.passive_notifications.page(params[:page]).per(20)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end

  # ログインユーザーのDM一覧
  def index
    @rooms = current_user.rooms.joins(:messages).includes(:messages).order('messages.created_at DESC')
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
  # 最新メッセージのデータを取得して表示するメソッド
  def most_new_message_preview(room)
    # 最新メッセージのデータを取得する
    message = room.messages.order(updated_at: :desc).limit(1)
    # 配列から取り出す
    message = message[0]
    # メッセージの有無を判定
    if message.present?
      # メッセージがあれば内容を表示
      tag.p message.content.to_s, class: 'dm_list__content_time__link__box__message'
    else
      # メッセージがなければ[ まだメッセージはありません ]を表示
      tag.p '[ まだメッセージはありません ]', class: 'dm_list__content__link__box__message'
    end
  end

  def most_new_message_time(room)
    # 最新メッセージのデータを取得する
    message = room.messages.order(updated_at: :desc).limit(1)
    # 配列から取り出す
    message = message[0]
    # メッセージの有無を判定
    if message.present?
      # メッセージがあれば内容を表示
      tag.p message.created_at.strftime('%Y/%m/%d %H:%M').to_s, class: 'dm_list__content__link__box__message'
    else
      # メッセージがなければ[ まだメッセージはありません ]を表示
      tag.p '[ まだメッセージはありません ]', class: 'dm_list__content__link__box__message'
    end
  end

  # 相手ユーザー名を取得して表示するメソッド
  def opponent_user(room)
    # 中間テーブルから相手ユーザーのデータを取得
    entry = room.entries.where.not(user_id: current_user)
    # 相手ユーザーの名前を取得
    name = entry.first&.user.present? ? entry.first.user.name : '退会済みユーザー'
    # 名前を表示
    tag.p name.to_s, class: 'dm_list__content__link__box__name'
  end

  def image_user(room)
    # 中間テーブルから相手ユーザーのデータを取得
    entry = room.entries.where.not(user_id: current_user)
    image = entry.first&.user.present? ? entry.first.user.image : 'no_user.png'
    # 相手ユーザーの画像を表示
    if entry.first&.user&.sex == '男性'
      image_tag image.to_s, class: 'icon_image_men_dm'
    elsif entry.first&.user&.sex == '女性'
      image_tag image.to_s, class: 'icon_image_women_dm'
    elsif entry.first&.user&.sex == 'その他'
      image_tag image.to_s, class: 'icon_image_other_dm'
    else
      image_tag image.to_s, class: 'icon_image_remove_dm'
    end
  end
end

app/views/rooms/index.html.erb
<div class="dm_list">

  <% @rooms.each do |room| %>
  <%= link_to room_path(room, anchor:'final'), class: "dm_list__content__link"  do%>
  <div class="dm_list__content">
    <div class="dm_list__content__link__box">
      <p class="dm_list__content__link__box__image">
        <%= image_user(room) %></p>
    </div>

    <% if room.notifications.where(visited_id: current_user, checked: false).present? %>
    <div class="chat_name_messege">
      <p class="dm_list__content__link__box__name">
        <%= opponent_user(room) %></p>
      <p class="dm_list__content_time__link__box__name">
        <b><%= most_new_message_preview(room) %></b></p>
    </div>

    <%else%>

    <div class="chat_name_messege">
      <p class="dm_list__content__link__box__name">
        <%= opponent_user(room) %></p>
      <p class="dm_list__content_time__link__box__name">
        <%= most_new_message_preview(room) %></p>
    </div>
    <% end %>

    <div class="chat_time">
      <%= most_new_message_time(room) %>
    </div>

  </div>
  <%end%>

  <%end%>

</div>

app/views/rooms/show.html.erb
  <% @entries.each do |e| %>
  <% if e.user.name == current_user.name %>
  <% else %>
  <hr>
  <div class="chat_profile">
    <div class="chat_profile_content">
      <div class="chat_profile_icon">
        <a href="/users/<%= e.user.id %>">
          <% if e.user.sex == "男性" %>
          <img src=<%= e.user.image %> class="icon_image_men_dm">
          <% elsif e.user.sex == "女性"%>
          <img src=<%= e.user.image %> class="icon_image_women_dm">
          <%else%>
          <img src=<%= e.user.image %> class="icon_image_other_dm">
          <% end %>
      </div>
      <div class="chat_profile_sentence">
        <div class="chat_profile_name">
          <b><%= e.user.name%></b>
        </div>
        <div class="chat_profile_detail">
          <%= e.user.work%>/
          <%= e.user.position%>/
          <%= e.user.uni%>/
          <%= e.user.annual%>/
          <%= e.user.location%>/
          <%= e.user.subject%>/
          <%= e.user.club%>/
        </div>
        </a>
      </div>
    </div>
  </div>
  <hr>
  <% end %>
  <% end %>

  <div class="DM_all">
    <% if @messages.present? %>
    <% @messages.each do |m| %>
    <div class="all_message">

      <% if m.user.name == current_user.name %>
      <div class="my_message">
        <div class="my_content">
          <%= safe_join(m.content.split("\n"), tag(:br)) %>
        </div>

        <div class="user_right">
          <%= m.created_at.strftime('%Y/%m/%d %H:%M') %>
        </div>

      </div>

      <% else %>
      <div class="your_message">
        <div class="your_content">
          <%= safe_join(m.content.split("\n"), tag(:br)) %>
        </div>
        <div class="user_right">
          <%= m.created_at.strftime('%Y/%m/%d %H:%M') %>
        </div>
      </div>

      <% end %>
      <% end %>

      <% else %>

      <div class="attention">
        <h3 class="text-center">メッセージはまだありません。</h3>
        <br>教育に関わる交流以外を目的としたマッチングやメッセージ、迷惑行為は禁止しております。
        <br>違反する事実や申し出がある場合は、お問い合わせフォームからご連絡ください。
        <br>健全なサービス提供のため、運営がメッセージ内容を確認することがあります。
      </div>

      <% end %>



      <div class="send">
        <% if @room.entries.size > 1 %>
        <%= form_for @message do |f| %>
        <%= f.text_area :content, :placeholder => "メッセージを入力して下さい" , :size => 70 %>
        <%= f.hidden_field :room_id, :value => @room.id %>
        <%= button_tag :type => "submit", :class =>"btn_send",:id=>'btn_send',
                data: { disable_with: '...<i class="fas fa-paper-plane"></i>' } do %>
        <i class="fas fa-paper-plane"></i>
        <% end %>
        <% end %>
        <% end %>

      </div>

      <h3 id="final"></h3>

    </div>